# This file was auto-generated by salt's setup on Tuesday, 22 March 2016 @ 22:03:14 UTC.

from salt.version import SaltStackVersion

__saltstack_version__ = SaltStackVersion(2015, 8, 8, 0, 0, 0, None)
